### ISSUE TITLE
Could not find com.android.tools.build:gradle-experimental:0.11.1

### ISSUE THREAD

**Issue by philburk** [gkasten/drrickorang#20]
On behalf of a partner

we encountered the following errors when building the app in the Android Studio.

Error:Could not find com.android.tools.build:gradle-experimental:0.11.1.

Searched in the following locations:

    file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/tools/build/gradle-experimental/0.11.1/gradle-experimental-0.11.1.pom

    file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/tools/build/gradle-experimental/0.11.1/gradle-experimental-0.11.1.jar

    https://jcenter.bintray.com/com/android/tools/build/gradle-experimental/0.11.1/gradle-experimental-0.11.1.pom

    https://jcenter.bintray.com/com/android/tools/build/gradle-experimental/0.11.1/gradle-experimental-0.11.1.jar

Required by:

    project :

**Comment by philburk** [comment]
It might be time to migrate away from the experimental gradle plugin.

http://tools.android.com/tech-docs/new-build-system/gradle-experimental

https://developer.android.com/studio/projects/add-native-code

**Comment by ggfan** [comment]
yeah, please migrate away from experimental! It is not supported in latest android studio at all.

**Comment by gkasten** [comment]
I do not know how to do that.  Can you help me please?

**Comment by gkasten** [comment]
I just talked with Gerry, he will look at this now.

**Comment by gkasten** [comment]
Should be fixed by the above commit from Gerry
