### ISSUE TITLE
Sometimes app does not display result from Latency Test

### ISSUE THREAD

**Issue by philburk** [gkasten/drrickorang#29]
To REPRODUCE:
Insert fun plug
Turn up volume to about 80%
Launch Loopback app
Press Calibrate Sound Level button

EXPECT
Just calibrate volume

ACTUAL
The Glitch test icon turns red indicating that it is running.
Sometimes the calibration sows a latency result.
Sometimes the Glitch test stays red and the Latency Test does not show a result.

If you run the latency test multiple times it starts to work.

**Comment by philburk** [comment]
This is very intermittent and hard to reproduce.
This is sometimes a symptom of call UI methods not on the UI thread.
The setTransportButtonsState() method makes UI calls.
It is called from a Handler in LoopbackActivity.java
The Handler is not on the UI thread:

    private Handler mMessageHandler = new Handler()

It may need to be on the UI thread:

    private Handler mMessageHandler = new Handler(Looper.getMainLooper())

Info here:
https://developer.android.com/training/multiple-threads/communicate-ui#Handler

Also I think lines 1104 and 1115 should set latencyStart not bufferStart.

**Comment by gkasten** [comment]
I have never seen this particular failure, nor was I able to reproduce it when I tested again today numerous times. Ideally I would prefer to see a fail -> pass transition before accepting a patch. However, in this case I am accepting the pull request without a transition, on the assumption that it will solve the problem based on the thread analysis.
